=== mycql/yapv/packages/core/src/schema.json
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/ViewSetup",
  "definitions": {
      "ViewSetup": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "name": {
                  "type": "string"
              },
              "displayConfig": {
                  "$ref": "#/definitions/ViewSetupDisplayConfig"
              },
              "sequenceConfig": {
                  "$ref": "#/definitions/SequenceConfig"
              },
              "labels": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/ViewSetupLabel"
                  }
              },
              "tracks": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/Track"
                  }
              }
          },
          "required": [
              "displayConfig",
              "labels",
              "name",
              "sequenceConfig",
              "tracks"
          ],
          "title": "ViewSetup"
      },
      "ViewSetupDisplayConfig": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "height": {
                  "type": "integer"
              },
              "width": {
                  "type": "integer"
              },
              "viewBox": {
                  "$ref": "#/definitions/ViewBox"
              }
          },
          "required": [
              "height",
              "viewBox",
              "width"
          ],
          "title": "ViewSetupDisplayConfig"
      },
      "ViewBox": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "height": {
                  "type": "integer"
              },
              "width": {
                  "type": "integer"
              }
          },
          "required": [
              "height",
              "width"
          ],
          "title": "ViewBox"
      },
      "ViewSetupLabel": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "text": {
                  "type": "string"
              },
              "displayConfig": {
                  "$ref": "#/definitions/LabelDisplayConfig"
              }
          },
          "required": [
              "displayConfig",
              "text"
          ],
          "title": "ViewSetupLabel"
      },
      "LabelDisplayConfig": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "type": {
                  "type": "string"
              },
              "style": {
                  "type": "string"
              },
              "vOffset": {
                  "type": "integer"
              },
              "hOffset": {
                  "type": "integer"
              }
          },
          "required": [
              "style",
              "type"
          ],
          "title": "LabelDisplayConfig"
      },
      "SequenceConfig": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "range": {
                  "$ref": "#/definitions/Range"
              }
          },
          "required": [
              "range"
          ],
          "title": "SequenceConfig"
      },
      "Range": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "start": {
                  "type": "integer"
              },
              "end": {
                  "type": "integer"
              }
          },
          "required": [
              "end",
              "start"
          ],
          "title": "Range"
      },
      "Track": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "displayConfig": {
                  "$ref": "#/definitions/AxisDisplayConfig"
              },
              "axes": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/Axis"
                  }
              },
              "markers": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/Marker"
                  }
              }
          },
          "required": [
              "axes",
              "displayConfig",
              "markers"
          ],
          "title": "Track"
      },
      "Axis": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "displayConfig": {
                  "$ref": "#/definitions/AxisDisplayConfig"
              }
          },
          "required": [
              "displayConfig"
          ],
          "title": "Axis"
      },
      "AxisDisplayConfig": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "distance": {
                  "type": "integer"
              },
              "width": {
                  "type": "integer"
              },
              "style": {
                  "type": "string"
              },
              "scales": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/Scale"
                  }
              }
          },
          "required": [
              "distance",
              "width"
          ],
          "title": "AxisDisplayConfig"
      },
      "Scale": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "width": {
                  "type": "integer"
              },
              "distance": {
                  "type": "integer"
              },
              "total": {
                  "type": "integer"
              },
              "style": {
                  "type": "string"
              },
              "label": {
                  "$ref": "#/definitions/ScaleLabel"
              },
              "interval": {
                  "type": "integer"
              },
              "ticks": {
                  "type": "array",
                  "items": {
                      "type": "integer"
                  }
              }
          },
          "required": [
              "distance",
              "label",
              "style",
              "width"
          ],
          "title": "Scale"
      },
      "ScaleLabel": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "type": {
                  "type": "string"
              },
              "style": {
                  "type": "string"
              },
              "distance": {
                  "type": "integer"
              }
          },
          "required": [
              "distance",
              "style",
              "type"
          ],
          "title": "ScaleLabel"
      },
      "Marker": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "displayConfig": {
                  "$ref": "#/definitions/MarkerDisplayConfig"
              },
              "location": {
                  "$ref": "#/definitions/Range"
              },
              "direction": {
                  "type": "string"
              },
              "labels": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/MarkerLabel"
                  }
              }
          },
          "required": [
              "direction",
              "displayConfig",
              "labels",
              "location"
          ],
          "title": "Marker"
      },
      "MarkerDisplayConfig": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "width": {
                  "type": "integer"
              },
              "style": {
                  "type": "string"
              },
              "anchor": {
                  "$ref": "#/definitions/ViewBox"
              }
          },
          "required": [
              "style",
              "width"
          ],
          "title": "MarkerDisplayConfig"
      },
      "MarkerLabel": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "text": {
                  "type": "string"
              },
              "displayConfig": {
                  "$ref": "#/definitions/LabelDisplayConfig"
              },
              "line": {
                  "$ref": "#/definitions/LineUnion"
              }
          },
          "required": [
              "displayConfig",
              "text"
          ],
          "title": "MarkerLabel"
      },
      "LineClass": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "coords": {
                  "type": "array",
                  "items": {
                      "$ref": "#/definitions/Coord"
                  }
              },
              "displayConfig": {
                  "$ref": "#/definitions/LineDisplayConfig"
              }
          },
          "required": [
              "coords"
          ],
          "title": "LineClass"
      },
      "Coord": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "x": {
                  "type": "integer"
              },
              "y": {
                  "type": "integer"
              }
          },
          "required": [
              "x",
              "y"
          ],
          "title": "Coord"
      },
      "LineDisplayConfig": {
          "type": "object",
          "additionalProperties": false,
          "properties": {
              "style": {
                  "type": "string"
              }
          },
          "required": [
              "style"
          ],
          "title": "LineDisplayConfig"
      },
      "LineUnion": {
          "anyOf": [
              {
                  "type": "boolean"
              },
              {
                  "$ref": "#/definitions/LineClass"
              }
          ],
          "title": "LineUnion"
      }
  }
}

=== mycql/yapv/examples/data/kitchensink.json
{
  "name": "kitchensink",
  "displayConfig": {
    "height": 600,
    "width": 600,
    "viewBox": {
      "height": 600,
      "width": 600
    }
  },
  "sequenceConfig": {
    "range": {
      "start": 1,
      "end": 201
    }
  },
  "labels": [
    {
      "text": "PSB0011",
      "displayConfig": {
        "type": "text",
        "style": "text-anchor: middle; font: 40px \"Arial\", sans-serif; fill: blue;"
      }
    },
    {
      "text": "CDS",
      "displayConfig": {
        "type": "text",
        "style": "text-anchor: middle; font: 20px \"Courier\", monotype; fill: orange;",
        "vOffset": 30,
        "hOffset": 60
      }
    }
  ],
  "tracks": [
    {
      "displayConfig": {
        "distance": 200,
        "width": 10,
        "style": "stroke: blue; fill: transparent;"
      },
      "axes": [
        {
          "displayConfig": {
            "distance": -15,
            "width": 2,
            "style": "stroke: orange; fill: brown;",
            "scales": [
              {
                "width": 4,
                "distance": -4,
                "total": 10,
                "style": "stroke: green; stroke-width: 2;",
                "label": {
                  "type": "text",
                  "style": "text-anchor: middle; font: 10px \"Courier\", monotype; fill: teal;",
                  "distance": -15
                }
              }
            ]
          }
        }
      ],
      "markers": [
        {
          "displayConfig": {
            "width": 14,
            "style": "stroke: red; fill: yellow; stroke-opacity: 0.4; stroke-width: 2; stroke-dasharray: 5,10,5; stroke-linejoin: round;"
          },
          "location": {
            "start": 1,
            "end": 101
          },
          "direction": "#",
          "labels": [
            {
              "text": "CRISPR 001",
              "displayConfig": {
                "type": "path",
                "style": "text-anchor: start; font: 10px \"Courier New\", monospace; fill: red; stroke: blue; letter-spacing: 5px;"
              }
            },
            {
              "text": "gene",
              "displayConfig": {
                "type": "path",
                "style": "text-anchor: start; font: 10px \"Courier New\", monospace; fill: gray;",
                "vOffset": -5,
                "hOffset": 20
              }
            }
          ]
        },
        {
          "displayConfig": {
            "width": 10,
            "style": "stroke: green; fill: purple; fill-opacity: 0.2;",
            "anchor": {
              "width": 18,
              "height": 30
            }
          },
          "location": {
            "start": 121,
            "end": 171
          },
          "direction": "*",
          "labels": [
            {
              "text": "CRISPR 002",
              "displayConfig": {
                "type": "text",
                "style": "text-anchor: middle; font: 10px \"Arial\", sans-serif; fill: red;"
              }
            }
          ]
        }
      ]
    },
    {
      "displayConfig": {
        "distance": 235,
        "width": 10
      },
      "axes": [
        {
          "displayConfig": {
            "distance": -15,
            "width": 2,
            "style": "stroke: red; fill: violet;",
            "scales": [
              {
                "width": 4,
                "distance": -4,
                "interval": 10,
                "style": "stroke: green; stroke-width: 2;",
                "label": {
                  "type": "path",
                  "style": "text-anchor: middle; font: 10px \"Arial\", sans-serif; fill: red;",
                  "distance": 10
                }
              }
            ]
          }
        }
      ],
      "markers": []
    },
    {
      "displayConfig": {
        "distance": 260,
        "width": 10
      },
      "axes": [
        {
          "displayConfig": {
            "distance": 14,
            "width": 2,
            "style": "stroke: green; fill: yellow;",
            "scales": [
              {
                "width": 10,
                "distance": 4,
                "ticks": [
                  50,
                  100,
                  150,
                  200
                ],
                "style": "stroke: red; stroke-width: 4;",
                "label": {
                  "type": "text",
                  "style": "text-anchor: middle; font: 10px \"Arial\", sans-serif; fill: red;",
                  "distance": -10
                }
              }
            ]
          }
        }
      ],
      "markers": [
        {
          "displayConfig": {
            "width": 14,
            "style": "stroke: red; fill: limegreen; fill-opacity: 0.2; stroke-width: 1; stroke-linejoin: round;",
            "anchor": {
              "width": 18,
              "height": 30
            }
          },
          "location": {
            "start": 180,
            "end": 20
          },
          "direction": "+",
          "labels": [
            {
              "text": "CRISPR 003",
              "line": {
                "coords": [
                  {
                    "x": 10,
                    "y": -20
                  }
                ],
                "displayConfig": {
                  "style": "stroke: red;"
                }
              },
              "displayConfig": {
                "type": "path",
                "style": "text-anchor: end; font: 10px \"Courier New\", monospace; fill: red; stroke: blue; letter-spacing: 5px;",
                "vOffset": 30
              }
            }
          ]
        },
        {
          "displayConfig": {
            "width": 14,
            "style": "stroke: limegreen; fill: red; fill-opacity: 0.2; stroke-width: 1; stroke-linejoin: round;",
            "anchor": {
              "width": 18,
              "height": 30
            }
          },
          "location": {
            "start": 130,
            "end": 170
          },
          "direction": "+",
          "labels": [
            {
              "text": "CRISPR 006",
              "line": {
                "coords": [
                  {
                    "x": -20,
                    "y": -20
                  }
                ]
              },
              "displayConfig": {
                "type": "text",
                "style": "text-anchor: middle; font: 10px \"Courier New\", monospace; fill: red; stroke: blue; letter-spacing: 5px;",
                "vOffset": -200,
                "hOffset": -10
              }
            }
          ]
        },
        {
          "displayConfig": {
            "width": 14,
            "style": "stroke: blue; fill: orange; fill-opacity: 0.2; stroke-width: 1;",
            "anchor": {
              "width": 18,
              "height": 30
            }
          },
          "location": {
            "start": 80,
            "end": 120
          },
          "direction": "-",
          "labels": [
            {
              "text": "CRISPR 004",
              "line": true,
              "displayConfig": {
                "type": "text",
                "style": "text-anchor: middle; font: 10px \"Courier New\", monospace; fill: green; stroke: green; letter-spacing: 5px;",
                "vOffset": 20,
                "hOffset": 100
              }
            }
          ]
        },
        {
          "displayConfig": {
            "width": 14,
            "style": "stroke: blue; fill: orange; fill-opacity: 0.2; stroke-width: 1;",
            "anchor": {
              "width": 18,
              "height": 30
            }
          },
          "location": {
            "start": 30,
            "end": 70
          },
          "direction": "-",
          "labels": [
            {
              "text": "CRISPR 005",
              "line": true,
              "displayConfig": {
                "type": "path",
                "style": "text-anchor: middle; font: 10px \"Courier New\", monospace; fill: green; stroke: orange; letter-spacing: 5px;",
                "vOffset": 30
              }
            }
          ]
        }
      ]
    }
  ]
}
